# Generated by Django 4.0 on 2022-03-08 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voteapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='x',
        ),
    ]
