# Generated by Django 4.0 on 2022-03-10 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voteapi', '0002_remove_vote_x'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='employee',
            field=models.IntegerField(),
        ),
    ]
