version: "3.9"

services:  
  reverser:
    image: nginx
    restart: unless-stopped
    volumes:
      - "./services/reverser/confs:/etc/nginx/conf.d"
    ports:
      - "80:80"      


  postgres:
    image: postgres:latest
    restart: unless-stopped
    env_file: ./services/postgres/.env
    volumes:
      - "./services/postgres/data:/var/lib/postgresql/data"
    
  auth:
    build: ./services/auth
    # @TODO Uncomment the line below
    # restart: unless-stopped 
    depends_on:
      - postgres
      - reverser
    env_file:
      - ./global-django.env
      - ./services/auth/.env
    volumes:
      - "./services/auth/src:/auth-app"
    expose:
      - "3000"
    # Do not forget adding "python manage.py makemigrations && python manage.py migrate" oOR MAYBE CHANGE BUILD SCRIPT
    command: bash -c "flake8 --exclude=migrations,__init__.py,__pycache__,settings.py . && mypy . && python manage.py test && ./wait-for-it.sh postgres:5432 -t 60 --strict -- gunicorn --bind :3000 --workers 3 --reload auth.wsgi:application"

  restaurants:
    build: ./services/restaurants
    depends_on:
      - postgres
      - reverser
      - auth
    volumes:
      - "./services/restaurants/src:/restaurants-app"
    expose:
      - "3001"
    env_file:
      - ./global-django.env
      - ./services/restaurants/.env
    command: bash -c "flake8 --exclude=migrations,__init__.py,__pycache__,settings.py . && mypy --exclude /migrations/ . && python manage.py test && ./wait-for-it.sh postgres:5432 -t 45 --strict -- gunicorn --bind :3001 --workers 3 --reload restaurants.wsgi:application"




