version: "3.9"

services:  
  reverser:
      image: nginx
      volumes:
        - "./services/reverser/confs:/etc/nginx/conf.d"
      ports:
        - "80:80"      


  postgres:
    image: postgres:latest
    restart: unless-stopped
    env_file: ./services/postgres/.env
    volumes:
      - "./services/postgres/data:/var/lib/postgresql/data"



