version: "3.9"

services:  
  reverser:
    image: nginx
    restart: unless-stopped
    volumes:
      - "./services/reverser/confs:/etc/nginx/conf.d"
    ports:
      - "80:80"      


  postgres:
    image: postgres:latest
    restart: unless-stopped
    env_file: ./services/postgres/.env
    volumes:
      - "./services/postgres/data:/var/lib/postgresql/data"
    
  auth:
    build: ./services/auth
    # @TODO Uncomment the line below
    # restart: unless-stopped 
    depends_on:
      - postgres
      - reverser
    env_file: ./services/auth/.env
    volumes:
      - "./services/auth/src:/auth-app"
    expose:
      - "3000"
    # Do not forget adding "python manage.py makemigrations && python manage.py migrate"
    command: bash -c "flake8 --exclude=migrations,__init__.py,__pycache__ . && mypy . && python manage.py test && ./wait-for-it.sh postgres:5432 -t 120 --strict -- gunicorn --bind :3000 --workers 3 --reload auth.wsgi:application"
    # command: bash -c "./wait-for-it.sh postgres:5432 -t 120 --strict -- gunicorn --bind :3000 --workers 3 --reload auth.wsgi:application"
    # command: bash -c "tail -F Anything"

  
  # api:



