# Generated by Django 4.0 on 2022-03-06 05:46

from django.contrib.postgres.operations import CITextExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies: list = [
    ]

    operations: list = [
        CITextExtension()
    ]
