# Generated by Django 4.0 on 2022-03-11 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_employee_restaurantmanager'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantmanager',
            name='is_manager',
            field=models.BooleanField(default=True),
        ),
    ]
