# Generated by Django 4.0 on 2022-03-09 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='mamanger',
            field=models.IntegerField(default=9),
            preserve_default=False,
        ),
    ]
