# Generated by Django 4.0 on 2022-03-10 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_mamanger_restaurant_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='restaurant',
            field=models.ForeignKey(default='c19292ec-e3ed-47ed-b4e1-1c1b79b9269d', on_delete=django.db.models.deletion.CASCADE, related_name='restaurant', to='core.restaurant'),
            preserve_default=False,
        ),
    ]
