# Generated by Django 4.0 on 2022-03-10 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_menu_restaurant'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='type',
            field=models.CharField(choices=[('M', 'meal'), ('D', 'drink')], default='M', max_length=1),
            preserve_default=False,
        ),
    ]
