# Generated by Django 4.0 on 2022-03-10 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_menuitem_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuitem',
            old_name='title',
            new_name='name',
        ),
    ]
